// Auto-generated from /public/sounds/ — 94 Epidemic CC0 tracks
// See sound-library.ts for classifier + situation mapping
export const SOUND_FILES_BY_CATEGORY = {
  "music-ambient": [
    "ES_A Small Hope - Center of Attention.mp3",
    "ES_Belief - Roots and Recognition.mp3",
    "ES_Boundless - Luba Hilman.mp3",
    "ES_Carefree Morning - Rebecca Mardal.mp3",
    "ES_Conifers - Dusty Decks.mp3",
    "ES_Glorious (Instrumental Version) - Adelyn Paik.mp3",
    "ES_Green Hours - Center of Attention.mp3",
    "ES_Happy Mood - Sarah, the Illstrumentalist.mp3",
    "ES_Head in the Clouds - Mizlo.mp3",
    "ES_Home (Instrumental Version) - Hector Gabriel.mp3",
    "ES_Home Again - DonVayei.mp3",
    "ES_I Will Travel - Elin Piel.mp3",
    "ES_In the Barn - Roy Edwin Williams.mp3",
    "ES_Kerfuffle - Jobii.mp3",
    "ES_Leap - Dylan Sitts.mp3",
    "ES_Lens Flare 3 - Peter Sandberg.mp3",
    "ES_Momentum of Life - Rachel Sandy.mp3",
    "ES_Motion Clarity - Out To The World.mp3",
    "ES_Movements - Elm Lake.mp3",
    "ES_Now or Never - Mizlo.mp3",
    "ES_O Que Ficou (Instrumental Version) - Clara Mendes.mp3",
    "ES_Open Fields - Johan Landqvist.mp3",
    "ES_Picturesque - Dusty Decks.mp3",
    "ES_Shadowed - John B. Lund.mp3",
    "ES_Solace - Staffan Carlen.mp3",
    "ES_Stay (Wide Open) (Instrumental Version) - Loving Caliber.mp3",
    "ES_Sunny Days (Instrumental Version) - Siine.mp3",
    "ES_The Redline Principle - Rachel Sandy.mp3",
    "ES_Velvet - Dylan Sitts.mp3",
    "ES_Wedding Plans - Von Meyer.mp3",
    "ES_Who Are You (Instrumental Version) - Zorro.mp3",
    "ES_Winds of Change - William Claeson.mp3",
    "ES_Winter Light - Shuta Yasukochi.mp3",
    "ES_quiet days (Instrumental Version) - Victor Lundberg.mp3",
  ],
  "music-dreamy": [
    "ES_Bohemian Fairy - Franz Gordon.mp3",
    "ES_Dreamlike Sunrise - Mandala Dreams.mp3",
    "ES_Sweet Dreams - Mizlo.mp3",
    "ES_Wonder - Henry Miles.mp3",
  ],
  "music-ethereal": [
    "ES_Havsdrommar - Center of Attention.mp3",
    "ES_Nattdrommar - Center of Attention.mp3",
  ],
  "nature-cave": [
    "ES_Ambience, Underground, Cave, Magic, Deep, Bubbling - Epidemic Sound.mp3",
    "ES_Ambience, Underground, Cave, Magic, Deep, Wind, Howling 02 - Epidemic Sound.mp3",
  ],
  "nature-forest": [
    "ES_Ambience, Birdsong, Chaffinch, Blackbird, Black Woodpecker, Coniferous Forest, Summer, Afternoon - Epidemic Sound.mp3",
    "ES_Ambience, Birdsong, Meadow, Summer, Birds Sing, Wind, Light Rustle In Trees - Epidemic Sound.mp3",
    "ES_Ambience, Forest, Singing Birds, Distant Traffic - Epidemic Sound.mp3",
    "ES_Ambience, Forest, Wind, Daytime, Creaking Tree In Wind, Little Andaman - Epidemic Sound.mp3",
    "ES_Ambience, Swamp, Mangroves, Morning, Mangrove Whistler, Middle Andaman - Epidemic Sound.mp3",
    "ES_Birds, Songbird, Rainforest, Dawn, Pied, Imperial, Pigeon, Ambience, Havelock Island - Epidemic Sound.mp3",
    "ES_Birds, Tropical, Rainforest, Morning, Rich, Bird, Drongo, Baratang Island 01 - Epidemic Sound.mp3",
    "ES_Rain, Vegetation, Medium Leaves, Drop, Tropical, Jungle - Epidemic Sound.mp3",
    "ES_The Bird's World - Elm Lake.mp3",
    "ES_Wind, Vegetation, Blowing Through Deciduous Trees, Leaves Rustling, Moderate Intensity, Winter, Afternoon - Epidemic Sound.mp3",
    "ES_Wind, Vegetation, Blowing Through Defoliated Deciduous Trees, Moderate Intensity, Crow Flying By, Winter, Evening - Epidemic Sound.mp3",
  ],
  "nature-night": [
    "ES_Ambience, Tropical, Mysterious Night, Cricket - Epidemic Sound.mp3",
    "ES_Ambience, Tropical, Rainforest, Night, Insects, Boobook, Middle Jarawa, Edge 02 - Epidemic Sound.mp3",
    "ES_Birds, Tropical, Rainforest, Afternoon, Singing Bird, Insects, Little Andaman 02 - Epidemic Sound.mp3",
  ],
  "nature-ocean": [
    "ES_Softest of Feathers - Calm Shores.mp3",
    "ES_Water, Lap, Gentle Waves, Splashing Against Rocks, Calm, Light Water Fizz - Epidemic Sound.mp3",
    "ES_Water, Lap, Gentle, On Rocks, Quiet, Peaceful, Calm Waves - Epidemic Sound.mp3",
    "ES_Water, Lap, Lake, Small Waves Lapping, Detailed, 1m, Loop 01 - Epidemic Sound.mp3",
    "ES_Water, Wave, Ocean, Beach Waves, Small, Lapping - Epidemic Sound.mp3",
    "ES_Water, Wave, Seaside, Waves, Inside, Mangroves, South Andaman - Epidemic Sound.mp3",
    "ES_Water, Wave, Small Waves Close, Bigger Distant Waves, 5 Meters From Ocean, Halmstad, Sweden - Epidemic Sound.mp3",
    "ES_Water, Wave, Waves Sweeping Over Rocks, Calm, Lapping, Scandinavian Archipelago - Epidemic Sound.mp3",
  ],
  "nature-rain": [
    "ES_Ambience, Forest, Birds Chirping, Light Rain, Light Wind - Epidemic Sound.mp3",
    "ES_Rain, Vegetation, Rain, Daytime, Incoming Hard Rain, Baratang Island - Epidemic Sound.mp3",
    "ES_Weather, Storm, Strong, Storm 2, Lightning, High Mountains, Bhaleydhunga, Himalaya 04 - Epidemic Sound.mp3",
  ],
  "nature-water": [
    "ES_Ambience, Tropical, Amazonas, Night Close, River Crickets, Frogs Bird Sometimes - Epidemic Sound.mp3",
    "ES_Ambience, Underground, Cave, Water, Dripping, Flowing 02 - Epidemic Sound.mp3",
    "ES_Ambience, Underground, Cave, Water, Dripping, Flowing 03 - Epidemic Sound.mp3",
    "ES_Water, Flow, Creek, Light, Flowing, Foam Details, Calm Forest 01 - Epidemic Sound.mp3",
    "ES_Water, Flow, River, Small, Soft, Burbling Between Stones - Epidemic Sound.mp3",
    "ES_Water, Movement, Small River, Continuous, Calm, Happy, Steady Stream 01 Schoeps (MS) - Epidemic Sound.mp3",
    "ES_Water, Waterfall, Small, Long Fall, Flowing, Trickle - Epidemic Sound.mp3",
    "ES_Water, Waterfall, Steady, Perspective - Epidemic Sound.mp3",
    "ES_Water, Waterfall, Top, Deep, Water Flowing Before Falling - Epidemic Sound.mp3",
    "ES_Water, Waterfall, Waterfall, Medium Flow 01 - Epidemic Sound.mp3",
  ],
  "nature-wind": [
    "ES_Weather, Storm, Snow Storm, Cold, Freezing, Heavy Wind, Whistling - Epidemic Sound.mp3",
    "ES_Wind, Gust, Mountain Wind, Very Strong, Cold Wind, Heavy Gusts, Jotunheimen, Norway 01 - Epidemic Sound.mp3",
  ],
  "sfx-breath": [
    "ES_Human, Breath, Breathing Mask, Close, Isolated, Heavy Breathing, Long Inhale & Exhale 01 - Epidemic Sound.mp3",
    "ES_Human, Breath, Breathing Mask, Close, Isolated, Heavy Breathing, Long Inhale & Exhale 02 - Epidemic Sound.mp3",
    "ES_Human, Breath, Female, Nose Breathing, Inhale, Exhale, Calm 01 - Epidemic Sound.mp3",
    "ES_Human, Breath, Inhale, Exhale, Smoking Cigarette - Epidemic Sound.mp3",
  ],
  "sfx-fire": [
    "ES_Fire, Burning, Bonfire, Moderate Size, Close, Crackling - Epidemic Sound.mp3",
    "ES_Fire, Burning, Burning Wood, Bonfire, Crispy, Soft Intensity, Loop - Epidemic Sound.mp3",
    "ES_Fire, Burning, Wood, Crispy, Medium Intensity - Epidemic Sound.mp3",
  ],
  "sfx-glass": [
    "ES_Glass, Break, Bottle, Smash x3 - Epidemic Sound.mp3",
    "ES_Glass, Break, Glassware Breaking, Big Smash - Epidemic Sound.mp3",
    "ES_Glass, Break, Window, Large, Smash - Epidemic Sound.mp3",
    "ES_Glass, Break, Window, Smash - Epidemic Sound.mp3",
    "ES_Ice, Break, Crack, Crispy, Close Up 11 - Epidemic Sound.mp3",
    "ES_Ice, Break, Cracks, Frosty, Crispy, Sharp Details - Epidemic Sound.mp3",
    "ES_Ice, Break, Ice Cracking, Push 02 - Epidemic Sound.mp3",
    "ES_Ice, Break, Thin Ice Cracks - Epidemic Sound.mp3",
  ],
} as const;

export const TOTAL_SOUND_FILES = 94;
